/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import backend.UserArray;
import backend.User;

/**

 @author Ryang
 */
public class MobileManager extends javax.swing.JFrame
{

    /**
     Creates new form overview
     */
    public MobileManager()
    {
        
        initComponents();
        
    }

    /**
     This method is called from within the constructor to initialize the form.
     WARNING: Do NOT modify this code. The content of this method is always
     regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        PlayerManagerButton = new javax.swing.JButton();
        practiceButton1 = new javax.swing.JButton();
        ViewMatchesButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        overviewLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(427, 390));
        setMinimumSize(new java.awt.Dimension(427, 390));
        setSize(new java.awt.Dimension(427, 390));

        PlayerManagerButton.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        PlayerManagerButton.setText("Player manager");
        PlayerManagerButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                PlayerManagerButtonActionPerformed(evt);
            }
        });

        practiceButton1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        practiceButton1.setText("Practices");
        practiceButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                practiceButton1ActionPerformed(evt);
            }
        });

        ViewMatchesButton.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        ViewMatchesButton.setText("Matches");
        ViewMatchesButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ViewMatchesButtonActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        logoutButton.setText("logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                logoutButtonActionPerformed(evt);
            }
        });

        overviewLabel.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        overviewLabel.setText("MOBILE MANAGER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PlayerManagerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(practiceButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewMatchesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(overviewLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(logoutButton)
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(overviewLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(practiceButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewMatchesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PlayerManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(logoutButton)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void practiceButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_practiceButton1ActionPerformed
    {//GEN-HEADEREND:event_practiceButton1ActionPerformed
        new LogPractice().setVisible(true);
        dispose();
    }//GEN-LAST:event_practiceButton1ActionPerformed

    private void PlayerManagerButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PlayerManagerButtonActionPerformed
    {//GEN-HEADEREND:event_PlayerManagerButtonActionPerformed
        new PlayerManager().setVisible(true);
        dispose();
    }//GEN-LAST:event_PlayerManagerButtonActionPerformed

    private void ViewMatchesButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ViewMatchesButtonActionPerformed
    {//GEN-HEADEREND:event_ViewMatchesButtonActionPerformed
        new LogMatches().setVisible(true);
        dispose();
    }//GEN-LAST:event_ViewMatchesButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_logoutButtonActionPerformed
    {//GEN-HEADEREND:event_logoutButtonActionPerformed
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MobileManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MobileManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MobileManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MobileManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MobileManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PlayerManagerButton;
    private javax.swing.JButton ViewMatchesButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel overviewLabel;
    private javax.swing.JButton practiceButton1;
    // End of variables declaration//GEN-END:variables
}
